services:
  python:
    build: 
      context: ..
      dockerfile: dev_tools/docker/python/Dockerfile
    working_dir: '/app'
    user: "$UID:$GID"
    env_file:
      - .env
    tty: true
    volumes:
      - ${SRC_PATH}:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${LOCAL_DATA}/gallery/:/home/user/Brushshe Images/
      - ${LOCAL_DATA}/.cache/:/home/user/.cache/
    environment:
      - DISPLAY=$DISPLAY
    #command: ["bash"]
    command: ["brushshe"]
    network_mode: none
    # privileged: true      # It needs for access to /dev/input/events* (but not enough for the tablet work)

